/*
 * generated by Xtext 2.10.0
 */
package org.xtext.ppd

import org.eclipse.xtext.conversion.IValueConverterService

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PpdRuntimeModule extends AbstractPpdRuntimeModule {
	    @Override
        override public Class<? extends IValueConverterService> bindIValueConverterService() {
        return STRINGValueConverter;
    }
}
