/*
 * generated by Xtext 2.10.0
 */
package org.xtext.ppd


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PpdStandaloneSetup extends PpdStandaloneSetupGenerated {

	def static void doSetup() {
		new PpdStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
