/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ppd.ppd;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Content</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ppd.ppd.Content#getVs <em>Vs</em>}</li>
 *   <li>{@link org.xtext.ppd.ppd.Content#getHs <em>Hs</em>}</li>
 *   <li>{@link org.xtext.ppd.ppd.Content#getSimpleContent <em>Simple Content</em>}</li>
 * </ul>
 *
 * @see org.xtext.ppd.ppd.PpdPackage#getContent()
 * @model
 * @generated
 */
public interface Content extends EObject
{
  /**
   * Returns the value of the '<em><b>Vs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Vs</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vs</em>' containment reference.
   * @see #setVs(VS)
   * @see org.xtext.ppd.ppd.PpdPackage#getContent_Vs()
   * @model containment="true"
   * @generated
   */
  VS getVs();

  /**
   * Sets the value of the '{@link org.xtext.ppd.ppd.Content#getVs <em>Vs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vs</em>' containment reference.
   * @see #getVs()
   * @generated
   */
  void setVs(VS value);

  /**
   * Returns the value of the '<em><b>Hs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hs</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hs</em>' containment reference.
   * @see #setHs(HS)
   * @see org.xtext.ppd.ppd.PpdPackage#getContent_Hs()
   * @model containment="true"
   * @generated
   */
  HS getHs();

  /**
   * Sets the value of the '{@link org.xtext.ppd.ppd.Content#getHs <em>Hs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hs</em>' containment reference.
   * @see #getHs()
   * @generated
   */
  void setHs(HS value);

  /**
   * Returns the value of the '<em><b>Simple Content</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Simple Content</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Simple Content</em>' containment reference.
   * @see #setSimpleContent(SimpleContent)
   * @see org.xtext.ppd.ppd.PpdPackage#getContent_SimpleContent()
   * @model containment="true"
   * @generated
   */
  SimpleContent getSimpleContent();

  /**
   * Sets the value of the '{@link org.xtext.ppd.ppd.Content#getSimpleContent <em>Simple Content</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Simple Content</em>' containment reference.
   * @see #getSimpleContent()
   * @generated
   */
  void setSimpleContent(SimpleContent value);

} // Content
