/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ppd.ppd;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Document</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ppd.ppd.Document#getPaper <em>Paper</em>}</li>
 *   <li>{@link org.xtext.ppd.ppd.Document#getContents <em>Contents</em>}</li>
 * </ul>
 *
 * @see org.xtext.ppd.ppd.PpdPackage#getDocument()
 * @model
 * @generated
 */
public interface Document extends EObject
{
  /**
   * Returns the value of the '<em><b>Paper</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Paper</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Paper</em>' containment reference.
   * @see #setPaper(Paper)
   * @see org.xtext.ppd.ppd.PpdPackage#getDocument_Paper()
   * @model containment="true"
   * @generated
   */
  Paper getPaper();

  /**
   * Sets the value of the '{@link org.xtext.ppd.ppd.Document#getPaper <em>Paper</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Paper</em>' containment reference.
   * @see #getPaper()
   * @generated
   */
  void setPaper(Paper value);

  /**
   * Returns the value of the '<em><b>Contents</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.ppd.ppd.Content}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Contents</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contents</em>' containment reference list.
   * @see org.xtext.ppd.ppd.PpdPackage#getDocument_Contents()
   * @model containment="true"
   * @generated
   */
  EList<Content> getContents();

} // Document
