/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ppd.ppd;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>GB</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ppd.ppd.GB#getColumns <em>Columns</em>}</li>
 * </ul>
 *
 * @see org.xtext.ppd.ppd.PpdPackage#getGB()
 * @model
 * @generated
 */
public interface GB extends Frame
{
  /**
   * Returns the value of the '<em><b>Columns</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Columns</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Columns</em>' attribute.
   * @see #setColumns(int)
   * @see org.xtext.ppd.ppd.PpdPackage#getGB_Columns()
   * @model
   * @generated
   */
  int getColumns();

  /**
   * Sets the value of the '{@link org.xtext.ppd.ppd.GB#getColumns <em>Columns</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Columns</em>' attribute.
   * @see #getColumns()
   * @generated
   */
  void setColumns(int value);

} // GB
