/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ppd.ppd;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>RJB</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.ppd.ppd.PpdPackage#getRJB()
 * @model
 * @generated
 */
public interface RJB extends Frame
{
} // RJB
