/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ppd.ppd;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Content</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.ppd.ppd.PpdPackage#getSimpleContent()
 * @model
 * @generated
 */
public interface SimpleContent extends EObject
{
} // SimpleContent
