/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ppd.ppd;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>VS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ppd.ppd.VS#getSpc <em>Spc</em>}</li>
 *   <li>{@link org.xtext.ppd.ppd.VS#isMore <em>More</em>}</li>
 * </ul>
 *
 * @see org.xtext.ppd.ppd.PpdPackage#getVS()
 * @model
 * @generated
 */
public interface VS extends EObject
{
  /**
   * Returns the value of the '<em><b>Spc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Spc</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Spc</em>' attribute.
   * @see #setSpc(int)
   * @see org.xtext.ppd.ppd.PpdPackage#getVS_Spc()
   * @model
   * @generated
   */
  int getSpc();

  /**
   * Sets the value of the '{@link org.xtext.ppd.ppd.VS#getSpc <em>Spc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Spc</em>' attribute.
   * @see #getSpc()
   * @generated
   */
  void setSpc(int value);

  /**
   * Returns the value of the '<em><b>More</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>More</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>More</em>' attribute.
   * @see #setMore(boolean)
   * @see org.xtext.ppd.ppd.PpdPackage#getVS_More()
   * @model
   * @generated
   */
  boolean isMore();

  /**
   * Sets the value of the '{@link org.xtext.ppd.ppd.VS#isMore <em>More</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>More</em>' attribute.
   * @see #isMore()
   * @generated
   */
  void setMore(boolean value);

} // VS
