/*
 * generated by Xtext 2.10.0
 */
package org.xtext.ppd.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPpdScopeProvider extends DelegatingScopeProvider {
}
