/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ppd.ppd.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.ppd.ppd.LAB;
import org.xtext.ppd.ppd.PpdPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>LAB</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LABImpl extends FrameImpl implements LAB
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LABImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PpdPackage.Literals.LAB;
  }

} //LABImpl
