/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ppd.ppd.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.ppd.ppd.PpdPackage;
import org.xtext.ppd.ppd.RJB;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>RJB</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RJBImpl extends FrameImpl implements RJB
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RJBImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PpdPackage.Literals.RJB;
  }

} //RJBImpl
