/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ppd.ppd.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.ppd.ppd.PpdPackage;
import org.xtext.ppd.ppd.SimpleContent;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Simple Content</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SimpleContentImpl extends MinimalEObjectImpl.Container implements SimpleContent
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SimpleContentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PpdPackage.Literals.SIMPLE_CONTENT;
  }

} //SimpleContentImpl
