/*
 * generated by Xtext 2.10.0
 */
package org.xtext.ppd.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.ppd.parser.antlr.internal.InternalPpdParser;
import org.xtext.ppd.services.PpdGrammarAccess;

public class PpdParser extends AbstractAntlrParser {

	@Inject
	private PpdGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	

	@Override
	protected InternalPpdParser createParser(XtextTokenStream stream) {
		return new InternalPpdParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Document";
	}

	public PpdGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PpdGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
